export const JOIN_ERROR_CODE = {
  NOT_JOINABLE_TIME: "APPOINTMENT_403_1",
  APPOINTMENT_NOT_FOUND: "APPOINTMENT_404_1",
  SLOT_NOT_FOUND: "APPOINTMENT_404_2",

  ALREADY_COMPLETED: "CONSULTATION_409_1",
  AGORA_CONFIG_MISSING: "CONSULTATION_500_1",
  RTC_TOKEN_ISSUE_FAILED: "CONSULTATION_502_1",

  AUTH_REQUIRED: "GLOBAL_401_1",
  ACCESS_TOKEN_EXPIRED: "GLOBAL_401_2",
  INVALID_ACCESS_TOKEN: "GLOBAL_401_3",

  INVALID_REQUEST: "GLOBAL_400_2",
} as const;

export type JoinErrorCode =
  (typeof JOIN_ERROR_CODE)[keyof typeof JOIN_ERROR_CODE];
